version: '3.3'

services:
  app:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    command:
      "bundle"

  postgres:
    image: postgres
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
volumes:
  rubygems:
  gemconfig: