#!/bin/bash

docker run \
  --rm \
  --name medical-exams-app \
  -w /app \
  -v $(pwd):/app \
  -v ruby_volume_rebase_labs:/usr/local/bundle \
  -p 3000:3000 \
  --network rebase_labs \
  ruby \
  bash -c "gem install rack sinatra puma && ruby server.rb"